---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pinepods-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: pinepods-db-secret
    template:
      engineVersion: v2
      data:
        DB_PASSWORD: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "7bb9fb26-61fa-4010-ab95-b4df00f8a970"
