# yamllint disable
# Generate locally, then encrypt:
#   kubectl create secret generic pinepods-secret \
#     --from-literal=INIT_POSTGRES_USER=pinepods \
#     --from-literal=INIT_POSTGRES_PASS="$(openssl rand -base64 24)" \
#     --dry-run=client -o yaml > secret.sops.yaml
#   sops --encrypt --in-place secret.sops.yaml
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: pinepods-secret
stringData:
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:rxjX0p0ZwCg=,iv:ou/z/XmNB8kFrwXBVaq5M8+9BfocwNfQeZhp+O/IHkg=,tag:8RSIsBWJTxVHmOhRvc5lIA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrL0JhTjI5andYcmRCemFX
        QllBWXBqV0JxeDA4MktvVXMyWXVocVg1MUNRCnNiRW8xMndENysyeW8vNDVYWndH
        REovMUdTaG5mWUNoTGNHTDJpL20vM0EKLS0tIG9uZ2NFOVhPOG8va2FWMTIyLzRJ
        dDJ2cGQ4R2tZeSttUXZiTCtKdkh1eHMKAb23cSC20yhdYmWWMH79QYIaNAqmSBFH
        4DAxJgy21fU9J/41UXaqQrD8gEgB+kx/7qPLBpm5hd67tMHHxqYMlg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T15:07:53Z"
  mac: ENC[AES256_GCM,data:FzbuKrOvlEYvXBAviYmxqQVFjFtbZiFvLF4l7BeMZaVtQAu3oDVsliJAYwiS5S3GXVZqYzPvDH14MNe7YzFy4+0YyfvhbYcCSjw7fuPO5M9qB9sybEOIKUMd3a9caG8zzdKAK5xOXPWlAX1uuq0ww3WVIDl2YMmIwTzWHrlGv6c=,iv:q1m1hkTztRSXlfHIQPQzONdfegY2carHEfY21xISCrs=,tag:aaGdARFqM0yc0QsKZ9SKxQ==,type:str]
  version: 3.13.3
