# yamllint disable
# Generate locally, then encrypt:
#   kubectl create secret generic pinepods-secret \
#     --from-literal=INIT_POSTGRES_USER=pinepods \
#     --from-literal=INIT_POSTGRES_PASS="$(openssl rand -base64 24)" \
#     --dry-run=client -o yaml > secret.sops.yaml
#   sops --encrypt --in-place secret.sops.yaml
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: pinepods-secret
stringData:
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:xi3MBTtt3dQ=,iv:KG0IANIH8OZkjiECvCXU3XB5K3VphcS8AZ9B7K3M5TI=,tag:rg5nyN/dpYRL2ek/JZBSXA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:TDcST27QsXcJG432Ot+gMH1EIUN0+vgCWFdkaKSqrYg=,iv:c+uuxLxCfE+b3AqLpuJ/L0A5ocsXh2zIpTbyFK+b51A=,tag:8ZL9YrFMdzdzpMfhAeIjiQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WUhaNm5ubDk1ZHIzemFp
        SU5odkUxTWgvVXhaNEJlSmdudDR0MVBRR1dBCm5PK0htdUdvVEdtTlJ6cWJtTnl6
        TTVveVhNMkJEL3EySE9EUTk5OGZmNEUKLS0tIG9rK29wd1ZiUWo2cmFYSlZwRncv
        Tk9kTWJFVW1HeTJaTHZidVJBYkNyajAKMX+FMuclpHDoCGxcKHW/dxxdpoq1xCDb
        PFsHdGssBIpcy35pIg2ShBGaQ8qcCaccu9elaNzPzORuvxWrKhSTFw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T21:57:29Z"
  mac: ENC[AES256_GCM,data:d3vJ05YFzr+qegWBHwuigdf1JdJcDSaXSaPKaHH3Jd7fpl+bcC4O24dpBqzTq0u5cqvGB3KH0SHxPdLdmmM+ef7hZPeNMEsKRzW677zEOqmaOOHqMIgAKeib0Htdnp9q8xWqnZbBCuy+F7twpH/gOKbawEI30cPXXD4+IvZYQK0=,iv:w+1t6MwfhpFusn9R6X0cGCbm2dJR4ujBDWQ2Uhnr+IU=,tag:djhQ6zec7aLrQQbxMJ4OZQ==,type:str]
  version: 3.13.3
