# yamllint disable
# Generate locally, then encrypt:
#   kubectl create secret generic pinepods-secret \
#     --from-literal=INIT_POSTGRES_USER=pinepods \
#     --from-literal=INIT_POSTGRES_PASS="$(openssl rand -base64 24)" \
#     --dry-run=client -o yaml > secret.sops.yaml
#   sops --encrypt --in-place secret.sops.yaml
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: pinepods-secret
stringData:
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:olEP92ZqzVY=,iv:rkbQzgB9Ru6WeYBlzaxSrRazhLgXWesHyHHlgsGhk1Y=,tag:1DuhyZrQ0r1VlpH8m+agJA==,type:str]
  INIT_POSTGRES_PASS: "" #ENC[AES256_GCM,data:b5623HUNwGg60gVF1SHV5X2Y/FdPXfeenT7/mq6ow5V+pJdtG9L2Lw==,iv:uXYu55469a5eoHxEUxAWywLwsNzV8u+qoNVVJ//SZOg=,tag:LnXVx5IdKE3zoXWtMC4bcg==,type:comment]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SFEzVmRsZkNOU2V6d2VK
        YXBrSW9KS05tbCtMOTVQVTNjM3l0ejNxSFdnCkg1bHlmdEFUQUY0by9IeWtPY1gr
        TWU1aU9NRXBXNC9xTkhsY0dVK1BjdjgKLS0tIEE1elU0djgwOFVxR0djZXFMTWts
        RVFST24wSWt1aHJlWWFsZCswM2p3eEUKhTgMudtTtrH0pHjmM+HqEF0mJ6hH6IZD
        sQeuiYUbd0wqhTwRwe0QVF4KVRV7QTUyAA/3bDYfjOyE6Es9mDFKIg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T19:01:54Z"
  mac: ENC[AES256_GCM,data:XnG4KUYSzR79Io1bMk7ZY4UmBwTXJu3QuqZDcN1Swm9Xh9BHsGGe/WxcMjnShf3B/li3Is7Qe8oUBX56Rb1imbCWx/tyaZBLqr/69uDTdSzwPj0COTGLH6fbZHtpQMEe8D2F3eGtikFhInEG0GVL/pYWcVkd50HItLPM0I5jV34=,iv:zrlv6TuNzt7NFbBQ4GOJjvAZNtr7nqu7FsHHkp/xgPQ=,tag:pNecqrv8XMM/lC+EZlzX6g==,type:str]
  version: 3.13.3
