---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tinyauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: tinyauth-secret
    template:
      engineVersion: v2
      data:
        TINYAUTH_SECRET: "{{ .TINYAUTH_SECRET }}"
        TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: "{{ .TINYAUTH_OAUTH_CLIENT_ID }}"
        TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET: "{{ .TINYAUTH_OAUTH_CLIENT_SECRET }}"
  data:
    - secretKey: TINYAUTH_SECRET
      remoteRef:
        key:
    - secretKey: TINYAUTH_OAUTH_CLIENT_ID
      remoteRef:
        key:
    - secretKey: TINYAUTH_OAUTH_CLIENT_SECRET
      remoteRef:
        key:
