module.exports = {
  httpUnsafeOrigin: 'https://pad.${ORG_DOMAIN}',
  httpSafeOrigin: 'https://pad-sandbox.${ORG_DOMAIN}',
  httpAddress: '0.0.0.0',
  httpPort: 3000,
  websocketPort: 3003,
  maxWorkers: 1,
  blockDailyCheck: true,
  adminKeys: [],
  base: '/data',
  filePath: '/data/files',
  archivePath: '/data/archive',
  pinPath: '/data/pins',
  taskPath: '/data/tasks',
  blockPath: '/data/block',
  blobPath: '/data/blob',
  blobStagingPath: '/data/blobstage',
  decreePath: '/data/decrees',
  logPath: false,
  logToStdout: true,
  logLevel: 'info',
  logFeedback: false,
  verbose: false,
  installMethod: 'docker',
};
