apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: llama-cpp-secret
stringData:
  LLAMA_ARG_API_KEY: ENC[AES256_GCM,data:icrqS0s5S9QllJqMNubuji6ncOR5557pXcZAh61OB5ugpzi6iO3nUBs+Htm0HM0ZKiPbP7JZjm64QqOgQzBr6Q==,iv:serVNV+QnilmSW0dtfAiCW2WEjSILKhEc1P0Bj7Ls+4=,tag:ckuEZva+VnvMlLwbMvwqow==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0djhtQmFhRDRkSWcxcFVQ
        eU1pYjR1OElpcmNtUjVxVEREZm1KZlRWeXpZClFqVXIyK0RGYjFGQzBsZHhySUY1
        U1VzeHNtcVpXQjJPNC9XSU9QcXNHLzQKLS0tIHFJQUNqaXY2dFEzMG9kODdFUEMy
        bGFaM2kwMVUzU2V3VUlHd3Z3bjRUTlUK2xLY40k0zypOhDTiLOnTXAphtJ599owg
        I+ODfHfCYAD1FZpbyKlby5+tY9gXmv+xaImvh7yJWEjIgYUqdg6wOg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-12T13:28:16Z"
  mac: ENC[AES256_GCM,data:Qd18MtwQG1IHs39pabeS+D6GZ7Fu4VvTh3wZUgvt7M5r7ObQa4Huv3hLcaOFJJUqrX++/LjPYmQAy9lHa8jKQ8qeMhRMU+Eag2j/ZeFeOUyTtIVz0d3L/G04sG7H5X3l8xSJKFHXMMMQ/yh7NmQfrYKhiMmbMtl/6fqE1lWFzN4=,iv:KwvtOqaDsTwfen8RnhPaqRYMXrcehoVqW7L9jd1F/Zg=,tag:SxjBgOqJ9nFMjKfJbwEzug==,type:str]
  version: 3.13.1
