# yamllint disable
#   kubectl create secret generic __APP__-secret \
#     --from-literal=PASSWORD="$(openssl rand -base64 24)" \
#     --dry-run=client -o yaml > secret.sops.yaml
#   sops --encrypt --in-place secret.sops.yaml
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: __APP__-secret
stringData:
  PASSWORD: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTStQYWVJK09jSTVmMkpj
        NlR6RDB3VE5odkxmN0ovSkd3Szc5R2VNUWtVCkw1ZXpseHZTd1pQdmFkRURScGs1
        blVLdzgrTC83NFAyTk1JTTR4U3RRc0kKLS0tIG9aV1RrWlppNjVHVTlMMVRmU1FE
        R3MzNEVqeWlIRGhKWDNMNFdRajVXZ28KtIDe5Ealgn3rt+4O/Jr93YbSA0dCwYzF
        hhwgmixlRs8w8kEWo0EryeCCotmkhqyFFUNOkVdFCXdVvIvVgaUHvw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T02:30:57Z"
  mac: ENC[AES256_GCM,data:vOlpToeevNldJhW80pId8QqfFYvA0JlY4ntwjC82pcF755ZrgryGxy7e0C8p262LVLGMMQtdmbSlWCeTUkZS7dU26R6v5ezOn/F5N6BpzTSCX1k6SsmkCfIDC4DThsNZ/CIvx/lod7bCejK7ZhMBdjK8/1yLpQPd7vmO9z+yXf0=,iv:nK6EzeLLV193G3a6dEYwm58M2aPPyJKE8HtupDYeMCE=,tag:UV//VdHWqWUHKmRqn9NU2Q==,type:str]
  version: 3.13.3
