---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: miniflux-db-secret
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgres://miniflux:{{ .password }}@postgres-1-rw.database.svc.cluster.local:5432/miniflux?sslmode=require"
  data:
    - secretKey: password
      remoteRef:
        key: "c6ef0e97-2091-44ac-99c2-b4df00f7c083"
