# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: miniflux-secret
stringData:
  ADMIN_USERNAME: ENC[AES256_GCM,data:ulkXxHA=,iv:4YrqYS8i0q8krs6JuUBvSUgLpHduVL5KGKbLILWA/6A=,tag:vs7PzFl4MBbvzH0TtUZsFQ==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:YFTdG5D+h5R443RQfLEU6MVGmoi+cGAZlwl0nQ==,iv:zI+xfNVE8byHykuFVlw1UaKacP7jVs9gGoXm6U5aoio=,tag:7Ml8XG2v5ZcfZ4iIs45wOg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:g+jOLUkwWAM=,iv:8fOJkF48g4T0amidlkZ0knucG4ybWQMxzzBmpe7dhAQ=,tag:BBjCTG9ZfL0OsjYtaq3UTA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:5sppuHQyd7tdMV76jV2nDQeumqoNzR0lL2fMKQ==,iv:QmV7hWOpZMC5e3vsA7h8/HykJOSTYKFFOLxiuoSvOyo=,tag:trQdOhwjOr97YZLbOmgG2w==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:JHz+TsQUeXymiz0t6noq0xQHRFMlfYSmyJoPq+EJTCh3OEQcpk2ns0lTcW0+dYfn+9gXWR4X87SObIsUIwt+rM8UHbixgaVrUHGRA5pMZCwp+T0QIPtYfvUD4g==,iv:MqP0IYBrzyqsWTXndVjUB9mk4f7q8ZsBUVsUbU5CiH8=,tag:L6e4bGxkUUVrBwH39uANWw==,type:str]
  OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:Cy5D2TvCqtACb1vJvGf/NP4WG1ijfMu5/+ZLQwg7HHo=,iv:z42kL1LKvkC8uzhAVPGLU/flyfE2UDqPvn8G70dgyk4=,tag:2wg6sa14vaA5zs8nnCS2jg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSR2RqLytHZ2FDazVOYUVr
        TS9zUjJSVWxXSGpFZnFUSGthM3FYbE9DSTNVClFQVTBYa3R1NjR0V3lOekxyYTJ0
        dHdXWHJQcFAwWXRpSEtjNlFpZWh2U0EKLS0tIHZSb1ptNW9RQitmcDViRmI2bGwz
        V3pSMCtNVUJibXdXa2FsNHN1MUpDalEKjtltg1wSc7ewd1gG92z91ooEQeqCcz5p
        ftSWOHfZf6CVtIwFWCMBCKoZMm/HiWD1SdTZSBuugkmflB/XRz2Zqg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-15T19:03:36Z"
  mac: ENC[AES256_GCM,data:ZAsj0fLTLP6fRvUCDPnq9m1udJzCVlIcleCGcYuzB8aHZt4pSNgt+OSqp+d7RXJoPsCYVPcPPopwD+fZVz3EaiAlaMHd1G8nyEJ52CvBnh0Z+9hBLmcRDWOwtiokgMWQT69e66qQF4ke/fGRaZo8JQwmyhFP/My9hXMeMYRVejQ=,iv:BaaE2uJRdulPWxRqOaGMWeKCbXqDqw8jijTob0q+HGg=,tag:yxhB3+vNfYX+57k2Bda2JA==,type:str]
  version: 3.13.2
