# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: miniflux-secret
stringData:
  ADMIN_USERNAME: ENC[AES256_GCM,data:Hl+8Op4=,iv:eVO5VkSbI7J0nD0zja5j+OgKhXBNamDty3qGGoTS9YE=,tag:hbw4XpUoopb8nc/DcpDGdw==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:vb6wTWv5IMsdn66k2LA/ICH6IHNeUG2Oz9P0JA==,iv:2C+ntJE069jMisuLIVlCK7F8S+9njdRxQ9mhlwA9OY8=,tag:xInlVm93QH22GlOn1UuIxQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:yRiVs+BY6f0=,iv:QLRia0TdP+RzPxZzNXJx3sg+ZSc2zMfvh92UUWMmYwg=,tag:wr7eiYV6GAtQNTswHvAtTw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:+JZcB5S+Kd/OmuwO87KD+QC44ZxGAO99mb3KMw==,iv:cKIRHgjayV12hn388UxvFS6T4SGqxXO85kkspOu+j84=,tag:BXHGRglqc7MMQ6QH6MEt+Q==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:VkiPTw3nMYe/tB5RzWwEI9zWiqYg4L+3zGfNeSEBfGEnQ+bxEylnZnlUZbp7VmVX4J5vlH2KU/mZs1j9tPKMFyjQ6falXf35ig8gEEpBtKHu72eZuhNsTWHnkg==,iv:o56w1z6RzQ1tCvPyS2T4Q6u6aCvroZzGqBM97Ag3FDc=,tag:QbQR4G8s44OQ5hs6c+zvfA==,type:str]
  OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:bojTaYOECfHPIyYlXQ4xC+Ps1UZ3NZ5DYhJhs2H6MbY=,iv:4NI/oUgL8HJazEncBY1p2TxsylOedmbpZ1cRFyV7e5Y=,tag:s2qEOSbWdoZu+FMzpERfpQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTm5pdHBWcGVWc09RY0Y2
        VFNVbkVoQVpVQ2wvYW4ydk5Ga3V3VHBRckNrCmdyTWNMVDFtdmpUM2tVWi9oTzJW
        WHE4M091azdTL1FFTjFmNzlJMDFIeTQKLS0tIC9jTFFZdnhCN3dPRkxPNVZ4SDBF
        NURJdDNjMTN4L0xPelh1UmdKMUE0WmcK8UcbhEytmLrWMkrsXC4acHe8f7AzjodE
        6Mn/Rj4ngAWog7qBQX4PU9+IvZth6t/jx+Qn9AO/0UXEFSWho7b0oQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-12T14:12:30Z"
  mac: ENC[AES256_GCM,data:YnRBPMaYyuGWXnVJndTmwaLyFRaMvaqPjOlifNLV1Q7ZwiaZ0e/DHvD9xDp8JgCKhzCBsm3uR/nd+UwPHYRFIOaYqDQRaAmKqp76Ayj1YTtl95r0HOn0xeXUixJ9fZi40j8APEIaSbBpCmaXKx5k1ym4tMJ97LHZBnedLmKxKTE=,iv:6ZowwWFFgWMyh/YnQ1Mm3W7HcZsfoNfnk9Y5yqrBAiw=,tag:JBX44w63TmgNsYC6xDJBKQ==,type:str]
  version: 3.13.1
