# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: miniflux-secret
stringData:
  ADMIN_USERNAME: ENC[AES256_GCM,data:Qk2ROKE=,iv:qDEO7BDEdh1yb2rZsWHUL71HOJawxmq7+/XXsgG3LMc=,tag:lqI1dp1/uHoSdgCTx6RgcQ==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:LtkGQoQ96Akt7+ZynLAid+W5c4HEyVXDmYmRzA==,iv:cccViRiRaAIxwHFY1+XqDO0IAkb45YOtXon97aVulY4=,tag:3bTZJAMH8JcL2AxXGnbtFQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:vXPSPXMI5w4=,iv:9MsUY+KEyqPlJ0o+WJ+7herGoIA3rGBkNAa59cwue28=,tag:a2uJ9ltPQI557U+S02JxIA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:wKu/Th6vcwuDCX6mVwbB0yHwZcDgbKW/m2W8Tw==,iv:s4DnPTqZ1PyFp8s8frKyJd5xOuiWPaUyY3kzKUWVhzA=,tag:4OO8xGffEfZehjK8I/kaNw==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:2KGRoXMFomFb0P3IQRkMuoCZepGspwUlYZrLRvQQIewGe7ExsvGBL2gidgAi3WZ0eeiaDWzLBlJeqF6xNJSnHIvX5iRTz2U4hCIuEAO2eFe5ERwCBeJud889gw==,iv:aL5XnbX4tMRwp0KgnGzbV4Wb6VN/3SRusg/+7kv/KVE=,tag:bndCqfo0gL/zLfST+/SM3g==,type:str]
  OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:widZrnIWjdDxGvUraJmWEG45uSEx85WVpQheJmS07R8=,iv:HfSwUP54c04ujUsODUVYLvJjza3Y3bFn9cQiF6cWjPo=,tag:7WaEjg+TuMWaYLMlzDQ13g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNUNIVWZJbDAxcldrSzdF
        SENwNDJhQVRyNjExSVZvcVUvbTE0clhiaUFnCnFYZ1Iwb0gxb0kycGs3dlR6bHVS
        S2pCTVFkUHdic0h3Y2tEcEZXZGxHalkKLS0tIG9Da1h4YThIN3N5bW4rRXM3eVor
        TXJ6djZoNW4xWVZoMlhHQ3VrdElDcVkKfGQUkC1ht8WhEAOnEHz3kZ+5VLCdzoK5
        j3D02mrtXjSRzjSOh50uL6LahVGcUjjD+OrANnTm6H7y4vWVJAuCYA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T15:07:53Z"
  mac: ENC[AES256_GCM,data:uQj63cbnBSEcsk5GHrq++FXr7owdeEP7QAzewy5Iu4ux/zhC4klIOJm946sXw32k45bjXcVpC12oqnV0PxWCyNMJolpnWm7xNHTlYdu1CY/kAQW0RP5ZQdB37DamekRKEKsIAnW2ZwCTHkdoSV+AruYuu4fPLbOZwccA/r2tcUQ=,iv:SLm+LHW4M9H6++rTw/B27OHrcz3guukPCwzfTA9eOuw=,tag:QRg5frxQJJwuwG38ovRuOA==,type:str]
  version: 3.13.3
