---
# yaml-language-server: $schema=https://schemas.recyclarr.dev/v8/config-schema.json
sonarr:
  sonarr_main:
    base_url: http://sonarr.media.svc.cluster.local:8989
    api_key: !env_var SONARR_API_KEY

    delete_old_custom_formats: true

    quality_definition:
      type: series
      qualities:
        - { name: WEBDL-1080p, min: 10, preferred: 25, max: 32 }
        - { name: WEBRip-1080p, min: 10, preferred: 25, max: 32 }
        - { name: Bluray-1080p, min: 10, preferred: 25, max: 32 }
        - { name: HDTV-1080p, min: 10, preferred: 25, max: 32 }
        - { name: WEBDL-720p, preferred: 25, max: 32 }
        - { name: WEBRip-720p, preferred: 25, max: 32 }
        - { name: Bluray-720p, preferred: 25, max: 32 }
        - { name: HDTV-720p, preferred: 25, max: 32 }

    quality_profiles:
      - trash_id: 9d142234e45d6143785ac55f5a9e8dc9 # WEB-1080p (Alternative)
        reset_unmatched_scores:
          enabled: true

    custom_format_groups:
      skip:
        - 158188097a58d7687dee647e04af0da3 # [Optional] Golden Rule HD

radarr:
  radarr_main:
    base_url: http://radarr.media.svc.cluster.local:7878
    api_key: !env_var RADARR_API_KEY

    delete_old_custom_formats: true

    quality_definition:
      type: movie
      qualities:
        - { name: WEBDL-1080p, preferred: 68, max: 85 }
        - { name: WEBRip-1080p, preferred: 68, max: 85 }
        - { name: Bluray-1080p, min: 25, preferred: 68, max: 85 }
        - { name: Bluray-720p, preferred: 68, max: 85 }

    quality_profiles:
      - trash_id: d1d67249d3890e49bc12e275d989a7e9 # HD Bluray + WEB
        reset_unmatched_scores:
          enabled: true
