kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: continuwuity-org-secret
stringData:
  CONTINUWUITY_REGISTRATION_TOKEN: ENC[AES256_GCM,data:2kfqQxy8ojHDJoFtVo2o3YiizFSxoWXzaYZfALh85oo=,iv:DkjN+cYn/EBcWuwPg2vU2AY5ZeuH4BXNZ2KpwCGog4I=,tag:Z58ug+0F3M//gqv0DohYmA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYy9sMTlkSEUxNjZtc1FV
        Sm9xVEkxTmRsRTZlK1VadXlSNUNrMWY4a1ZJCnd0VENoRzFOMGhIR2J2Y0tPNGx3
        VVNxUVBFaTY1SWdqSVNkeFpYa0JIT0kKLS0tIG1GV0RvNnhXWE5aRXdsTzk4bzh4
        Z2VReHdxS1ZZNGEveEVJZUh3ei9zU2MKKhkRQj3tLZlxbUZ4MFGANdp7u6JUOCXH
        QGGk0W/9zYYGR/U8DzXvLZ8drOO/UhSCEZoKyQrkbdQ3jsfK0C+83g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T19:01:54Z"
  mac: ENC[AES256_GCM,data:knoeCwx65tmdavd+GvIkBzHrQXzTt5EbhvaZPXXWWMrusFgrhlZs2VyfPnBf4PJP2Np0fY/VvQ7IxhtdwT+fczEZJ7DP+Iai0MWIHeHJMmh2HUfmc2K+LzeePw5ETy+Ksj+i9oYeUN7r8GDBVGFtkIofQMPmpI04ex77J3m04dA=,iv:JXe4Vr8GBT21LJDvcMqIr3nkV2osAERnqhKV1qTYSF0=,tag:Sl53m2j2MQP6rn0dey5J0Q==,type:str]
  version: 3.13.3
