# yamllint disable
# Generate locally, then encrypt:
#   kubectl create secret generic searxng-secret \
#     --from-literal=SEARXNG_SECRET="$(openssl rand -hex 32)" \
#     --dry-run=client -o yaml > secret.sops.yaml
#   sops --encrypt --in-place secret.sops.yaml
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: searxng-secret
stringData:
  SEARXNG_SECRET: "" #ENC[AES256_GCM,data:eiW5xsBJxWq6q7xMSONoXyAgoi1dgzmHPFGWTcGAxUkkVxihnzK9uA==,iv:TIoA+jYAY0DxuL7kO0rr+vFBJswVOpaLR1Olqhe+dJs=,tag:4jqSDbbLB5CwKl+L2uIMEg==,type:comment]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUUwvZ2d4eFgxMkRmRkp6
        UGFJK3cxY2dlT2dzb21wUlByMUlNcEFCOXdrClJ0NTZsU0Z5VWNzNHhOZkpZN0dU
        WFVpbzdjajErOFRQUEExTUM4WjMrUDgKLS0tIDR5bDQvK2tNT3RkQTM1WVlMS0ZR
        dDJYenYxZjRFZDMyNmx1cG10NDF0R0EKCF3Q8tjeQrprnYoy+H2HV1PGOFYLD6jT
        +sVKEJCIK1QZCnczsiiMmz88TSt/XWkWJjAywMW+DnAdo6MzpCwzwQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T19:01:54Z"
  mac: ENC[AES256_GCM,data:Gf5AMXRx/rbZEsc7w70PhSYQs/gvbZTFgIFczjy5fJ7WSEWbH3PulY4DzCzSvfAJUgfosFXbuEglW9K9zhSktSFjBOiiXoFKvgUcWwf9yqBGjGK4++lWbolnLL1QOCAuV/ruqc8ml2oi/EwAexCdC287BfJiDFNAOpuG/zzkfIw=,iv:F1R+zsH8S6IgJfXtKlQp0mn9sIRnhA0fu9lhGPnPAnw=,tag:bByutRVeWhsyzpkIjZ9nUQ==,type:str]
  version: 3.13.3
