# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: radarr-secret
stringData:
  api_key: ENC[AES256_GCM,data:yvU0UR9kwa5r9MiEfmLida5cDBVTAKh6zCDkMQ29DRI=,iv:D6vZq9fzU9xefzbm569xLmeZQ5CBT2DqW1MEXQS026k=,tag:A4z3c3rMWyFuxO7i5xI+9w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WDBRVU4vVFJSL3dYZWFs
        b3pkS1krRXZJRVRoR2lsZkJFZjc5Yi9pRGpFClFiYjh5UVNQQ3JHWWJtMHd6NWlo
        Qjl6M0FMZWc3cks4c1NKNTFrWVVkOTAKLS0tIEFrWmw1czh4N28vODkzZiswZ0g4
        VXBrRGd5ZWNqdXVJb1IyUWorVzlFNDAKI9seZfJuqHd5964OKw3bW279x5yoeY16
        sdOmZgs4ug3XBRPFs0v7pNcUIiI77Aag3ll7QdDr7ehR8aKX84XfMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-15T19:03:37Z"
  mac: ENC[AES256_GCM,data:YwlwbF80OwzwfqPpbzTdqSGQ84bv5b96kHG26nV+eF02CiM5Nk6qK7Qmr56j/ZYz0INGUEHFm3gbdNs7dIeak8kATa3LZXECh7JYlJHG6vxudWI41O1irPuKcqsrSps/PQZDPsL8lJBdDXbcysmYLCm1czA/PBfD0zzb+6yX9yA=,iv:GPaccX2pAvRfapZ4T8rT5yLOGb2kdPsFTDLJYBwJQEU=,tag:DPEkLZD58qczNPZISekodQ==,type:str]
  version: 3.13.2
