---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ntfy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      ntfy:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            # renovate: datasource=docker depName=ghcr.io/liana64/ntfy
            image:
              repository: ghcr.io/liana64/ntfy
              tag: v2.24.0@sha256:f8a9b104313b87cc24ae4f775f39e6328205b57dff6ede3eaf098a91e5d79f59
            args:
              - serve
            env:
              NTFY_BASE_URL: https://ntfy.${PERSONAL_DOMAIN}
              NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
              NTFY_BEHIND_PROXY: "true"
              NTFY_AUTH_FILE: /var/lib/ntfy/user.db
              NTFY_AUTH_DEFAULT_ACCESS: deny-all
              NTFY_CACHE_FILE: /var/cache/ntfy/cache.db
              NTFY_ENABLE_LOGIN: "true"
              NTFY_ENABLE_SIGNUP: "false"
              NTFY_ENABLE_RESERVATIONS: "true"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /v1/health
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: ntfy
        ports:
          http:
            port: *port
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-traefik-middleware-chain-no-auth@kubernetescrd"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Services
          gethomepage.dev/name: Ntfy
          gethomepage.dev/description: Notification server
          gethomepage.dev/icon: ntfy
          #gethomepage.dev/widget.url: "https://rss.${LAB_DOMAIN}"
          #gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_MINIFLUX_TOKEN}}"
        hosts:
          - host: &host "ntfy.${PERSONAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: ntfy-tls
            hosts: [*host]
    persistence:
      data:
        storageClass: cluster-nvme
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
        globalMounts:
          - path: /var/lib/ntfy
      cache:
        type: emptyDir
        globalMounts:
          - path: /var/cache/ntfy
