# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: ntfy-secret
stringData:
  NTFY_AUTH_USERS: ENC[AES256_GCM,data:HrdBn7VObGoCvZK444PuI2fsbqRC9Cn4BFO79GQ6m6EeIM1Ve+Zbg3anq6bLyYoojKikjCrEuLIvx02sbTaAsI5Yxy83lhcWy43NyvXE,iv:BbClzu+gD9iffFJ86ZdUdlAMj0F90Vwhzn7NoEsyMO4=,tag:w8Ga6fu9RMlIJRdF9P9xbQ==,type:str] #ENC[AES256_GCM,data:/yi+4Gbp3IQD2AfuaMZPf5QOZ5zG/JDl5TrzzVfACF0=,iv:PwIEHms/Lh5z7ei7SdpoCXU/rph3Ndg+xAMt0y+t2fI=,tag:Whq8ux6XZ8qO3nZ8Ze/PXw==,type:comment]
  NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:dnU7IMwsIbaIOaRvMJZm1PzGfu0ss6t2AnC5s5fllE//ffWwq5IRUqiFzxP6//rcQ3Fb4XU+vmuYEw==,iv:S7OYtCfR1AVwTl2PgH3DHICWC9pZkWfg9meBYUikGrQ=,tag:49bkGXvvruBUXAgCsUu7mw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Z2E0eVlPbU11WFoxTnQ0
        Nm1aNldrZ1U3ZkdGT1NXclROaFBocmxaQjA0CncybmpjVGpYUmJibzR0ejkxSHli
        cGZWVXUybjVWdFRKQnk3eElDNmlqaWMKLS0tIEJoRFVaV213M2xMeFNpZWFUb1Ey
        anl0MEpUS3BvK1JUWEhja29GMHMxdU0K3VZHsACO6B3uPVzyVJ7H2mOsuR/WkiuL
        5Bl3adknTu7wpMM/MZ7XHMhpQDkg/cfO/RfFIby4Mt5QFR3b7HG8BA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-26T00:43:39Z"
  mac: ENC[AES256_GCM,data:F+FbZa7Ydh2u7NL1cJ1Esb+lP3ofPOgXFohDr2mgCoqF3YGJRC//aM3Wo+B3EXdOsrcGD3M3Ta7wdbutu9DBerLM2WYX8c4t7CjR0QK/u0MotIboJbxnI0UIMrRT6kzg1uXV7aFYth1Bclb3g/fs8FWKtjsueGHDuj0CIs12Olo=,iv:QSu7jgaG5C+kXMvE7skJe1qZOnCLq0Np9XZzbFWXgNc=,tag:PwX0vZOhHhkkS9Wwn9s4YQ==,type:str]
  version: 3.13.3
