---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meet-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: meet-db-secret
    template:
      engineVersion: v2
      data:
        DB_USER: meet
        DB_PASSWORD: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "608ca4b5-aff7-4e27-9305-b4df00f92d8a"
