# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: meet-secret
stringData:
  DJANGO_SECRET_KEY: ENC[AES256_GCM,data:Icd8RM/m0UD7PbR7H99NTBUX+zjXyFAKZCVClvuY0OElwtoWovCsfcdpKxukgItoaIBPBd1efi3PHItlqByd,iv:JQKeqbJ8H/+UzAMyf2L3EoOAwTjQK5nl4khjpxBZU64=,tag:MxrK5gzMKNJS9ODjlt6rTA==,type:str]
  DB_USER: ENC[AES256_GCM,data:f8dMbA==,iv:LfvrIDeu63vUwypsPOF7eo52JshoR3EgeHiqicK83AM=,tag:01skBlOPYbzLefPQonmVYw==,type:str]
  OIDC_RP_CLIENT_SECRET: ENC[AES256_GCM,data:YJS/2AqlozbnVrlzuepTl6kUtKpGcwsXJuT0noIUk90=,iv:6CSX3pXrzaqhZ5GT1gR+nXVpWsdKb9u8VDj6lrnK3GI=,tag:ziLOmmDhArKB9piY0ELpFw==,type:str]
  LIVEKIT_API_SECRET: ENC[AES256_GCM,data:XrA9pBCQw43jNWpXpnl3AKIjigV4DRUqPlV0DPgyuzAS/T05eYCIGbSmbQuVNnf9,iv:pu+KIk4uRfRG02YqvH7wo9K/tcd4W9HRcwCKBlHJzgQ=,tag:swHdfnQ+s5K0v2yKQe+Wkw==,type:str]
  LIVEKIT_KEYS: ENC[AES256_GCM,data:x1j/BaGglnNz+izGM7BQ1orf09UIrtzBGfI8HeHYjs9MFzfkP4hWm+pIxzVwuuYGs7KVx85b,iv:ifORx8ZgufvdbKoqp9CUqSlF09eU47KjVd9flW9xsO4=,tag:UmJqhK5VT+PFAdkF1oDyiw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRzBEOGVuZk91QkpkZGdO
        bUNmVjdoeGkwSzNGbHN0UVVaclNFU3ZCbXkwCjBybFVYUGovVTNsS1NibGxzY3Iv
        ZFFqOHVYUVcvMU8vWDZvMGE2aWdWc1UKLS0tIEM3Tk1JcFRIbUZTdHZZcmNkVWVO
        bG96aE9wUUkvaTlLdHA2RlpTZ0FUZVEKinrVELKjvZZFI2hZyaNfUesc4tOLiFmW
        M3TCd7ymBSioZCyqPtMbUqByltQPP3loAJjQPAl6YW27oSTot9ltHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T15:07:53Z"
  mac: ENC[AES256_GCM,data:CJgzG/53bG5fw0nnIRAaxRmeTl/s+bYBJaGSo0kf5zRAVMwkP/xu0Dwpdi1c1TbiuoVA7KpirLg9z6l4CXHsLYbjX30T2hSqcoXfHAkir4AMI5aRWPf0MTNwny7NlrncxdQA3iAsY7UlkqoCOZnz+jKAUuUf9Y/Ahz8Ma++dkYQ=,iv:nnzF0cqj9D7a1IsKigeHoigHrixCj+f2jmMP6wABNHc=,tag:r5VCJimhxlE6NjDqjsqWSQ==,type:str]
  version: 3.13.3
