# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: meet-secret
stringData:
  DJANGO_SECRET_KEY: ENC[AES256_GCM,data:uUDUJjmtw7D4n4M5/TftCo8bj8yFj3NSTLUTJtcMdUdfsWJBmnxkPFjHtfaAbefdEP5QLHJdI20tPa8lLJZi,iv:yE3+l+O0ylAnC9xrGHGmth+UdEbiNX80r1t3LNLQKVc=,tag:6hyueqvthNnyW6NUehu+lg==,type:str]
  DB_USER: ENC[AES256_GCM,data:sCCHrQ==,iv:uVxylGahb49tW0ZVLB+EdOaJZ5XMEwb/VmzAJR2Hbn0=,tag:YCrVWDeek37zQ4PBZi+nTA==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:W9FTfJj1/CIAllSIT90xbK4VzsGzRT/G/5K4ykUEXNA=,iv:cGwn9fK3XxqC7VfibPTH8aabcj+8MOnBunVUTKTjols=,tag:jtvyXlioiKwJ2x/A9ngcbg==,type:str]
  OIDC_RP_CLIENT_SECRET: ENC[AES256_GCM,data:FdZ7r3VhcGimeyl5qKG5oBvoq8mp67ZRoaQNu7+dynA=,iv:Ue5lA/Buu6vN5P7int9ven6kZT1rWziedMsolbGxYXU=,tag:jLO7swZX8nbqOwHzW2/3+A==,type:str]
  LIVEKIT_API_SECRET: ENC[AES256_GCM,data:o4WnxMjjn1ECu5ztopj6a1GeT4lEn79EE9neBfOTbF8KeKa4D3YCRkoiC8dheMwD,iv:M0jrcIh6Ug0L0tdcxVbKSofzK53mp/mpOa8DIt3KIQg=,tag:WnnY20BErWWWPbRmrbKl8g==,type:str]
  LIVEKIT_KEYS: ENC[AES256_GCM,data:Zf135E0FUx6KMaVerdz1BnMV2PWEcx/gBknic/fj+JIzFNv1CfLIZf4UYlceufTwnkjS/MyM,iv:l7E8EixVZDW2gkdMY6DPLH/go6tUMMoxkAOrm6YFVuU=,tag:o0tIyBBlw72P4VwsBeOtrA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIKzlRdTZ4bUZ1dzFrcUJH
        UVF1OTRlcXFwN1ZYZzJaQnJ4QWNBNXRKYXh3ClE1aElQNXJ5RHZJS2dORlhZYWxF
        ZjFKMTJEaFJ1T3hOU1A1b0Jzc0tpb3cKLS0tIEtpc1FVUTlObTRJa3FLb2huOW9B
        d1U0eXBjalpuUUxjWk4zRGJ0V1c5U0EKgu10/rLxEXSstn6ONzsyeMW6Za9xlbI5
        u1DqYqZPv+06vexqGGJspso1JhGLmYcS1+0bH3yRuQf2bHEQUW9GZw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T23:42:25Z"
  mac: ENC[AES256_GCM,data:hYI7jsnnqK45Cy1D3lZowWuWtEMFo68MtcbA34M0XDPRpTmceFoUZ1G8lIF7k8Wl10uvmn1Lcu0ZgF9cTpeUO6vzm8kc/9AUNmes9jsX9O7/T8oL9fTWpZ+RFEOy5jIx0ayw9ZWlEmtM8QPgmhhv1k6cooSAKPN0P/EiyJCgnHM=,iv:T5vBgMtVccxLYS9KHrOnQ2kjgnz8VahM25GMEe848v0=,tag:PvcMXwTsZNEZweYB6yJDcg==,type:str]
  version: 3.13.3
