server:
  host: 0.0.0.0
  port: 8080

theme:
  background-color: 240 8 9
  primary-color: 250 60 75
  contrast-multiplier: 1.1

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: search
            search-engine: https://kagi.com/search?q={QUERY}
            new-tab: true
          - type: calendar
            first-day-of-week: monday
          - type: weather
            location: Chicago, Illinois, United States
            units: imperial
            hour-format: 12h
          - type: markets
            markets:
              - symbol: ^GSPC
                name: S&P 500
              - symbol: NOW
                name: ServiceNow
              - symbol: BKLC
                name: BNY US Large Cap
              - symbol: INOPDX
                name: INOPDX
          - type: bookmarks
            groups:
              - title: Links
                links:
                  - title: Bookmarks
                    url: https://bookmarks.milberry.org
                  - title: RSS
                    url: https://rss.labs.lianas.org
                  - title: Labs
                    url: https://labs.lianas.org
                  - title: Forgejo
                    url: https://git.milberry.org
      - size: full
        widgets:
          - type: hacker-news
          - type: rss
            title: Forgejo activity
            limit: 15
            collapse-after: 5
            feeds:
              - url: https://git.milberry.org/liana.atom
                title: liana
