---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: grafana-db-secret
    template:
      engineVersion: v2
      data:
        GF_DATABASE_PASSWORD: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "f83be31b-e809-4a1c-961b-b4df00f8edce"
