---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dashboard.yaml
  - ./dashboard-snapshots.yaml
  - ./dashboard-restic.yaml
  - ./networkpolicy.yaml
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./externalsecret.yaml
