## yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: grafana-secret
stringData:
  GF_DATABASE_USER: ENC[AES256_GCM,data:q+xzdd7YtQ==,iv:dSg5rRP2gaudRrbfvjGsHnCZfHM6ms08EP69F580Puk=,tag:bLaZY7H2lkojHIZAcG1STQ==,type:str]
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:e7rdKOzpLGGzP/0cCttoPwocFUfN5ofDA9rHm4n5ifpjlt4eMBwspRUA2jLzh5Zp,iv:vk3rTH9W5fAIdPEm+FR6T4PKShmvSvs/7A9n5Dze0OM=,tag:JP9NJpBf/j6jrJx9Gh9VjQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWlR1WHVndUl0bXVRZ2tS
        b2JFb3JkS3pZMVRrdXpEbnpwcjBaQnNLVnhnCmNvS0ZiNTJ1d3FYRnVqNnYyNmtV
        Q2NEYjVMWkorSnFONmhZL3ZnaW1Ga2MKLS0tIDJHbTV0VVpUbHp1b05FNE54TDRR
        OFZiVVN1SWI0QUpSQ0JrUnM2QnlPZ0EKZNFL52KNC4FysuhVbIqEGYlSZzKL4fXC
        qzYwiaGFZFjQjpk8tRHEV0h2qqd7oReoaqYZwfSW9nOqL5HlUGktCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T15:07:53Z"
  mac: ENC[AES256_GCM,data:Z8FbRL1a8jCp3VbxIY63ArtdJ83nm7Pod/1FTRzLRIpPHVHaSBtjNE7sO46s+j/Ed5+TIMF1gJak1q9hcdEDt56ZSbpXhii1RcaW5ZbbsUhII1mP0c31E2xzszOMGYjs3b+MbSJX+sgV18ZQ5fL2Ug9lObe2zsiCqb3ltj1oQEk=,iv:SdHmcdZC3axqDDk1usFoCMaP+LyjgUeZ87/kHWddQRQ=,tag:x+0ifAY0+7pEB3oVxrJLDQ==,type:str]
  version: 3.13.3
