---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eek-config
data:
  config.toml: |
    listen = "0.0.0.0:8551"
    gateway_keys = ["$${GATEWAY_KEY}"]

    [providers.fireworks]
    base_url = "https://api.fireworks.ai/inference"
    api_key = "$${FIREWORKS_API_KEY}"
