---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app eek
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: eek-provider-secret
    template:
      engineVersion: v2
      data:
        FIREWORKS_API_KEY: "{{ .FIREWORKS_API_KEY_EEK }}"
  data:
    - secretKey: FIREWORKS_API_KEY_EEK
      remoteRef:
        key: "716e729e-b39b-42da-bcea-b48a001d9464"
