apiVersion: v1
data:
  GATEWAY_KEY: ENC[AES256_GCM,data:Bv9/8FcpgAdhLPyzn4ObBoqD6Z+1f97RNHoMwlnpJ+8XfPm+KLoZ+9zRypii2HGbBIvqQR/36CbsYrBLRgbTSIkfVlPotnwWY0j07g/vgvYHJ4Wymaqf9Q==,iv:fwwlwy9UOCjvR5QxwPFLdo0WXmFfGPH5H8JxAmlcs3w=,tag:WtRQTgyVd6KjJzgiQHPlZw==,type:str]
kind: Secret
metadata:
  name: eek-secret
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SlJsSnFyUmVVSXp3ckVQ
        c25mRzlRTVYzV2d5Mll5emVjMUxnQzR3MEcwCm4zWENsUG9jNUVmTm9PWEZmMFFL
        TU90SDQ4eTBuMGNpekwyQmUzMlQ4bFkKLS0tIHIvYjdEc0I1SStYNnVFMkUwSDhi
        dVF3SFVTMzJzQlp6UlowVzhJWnVqc2cKTVLPn1sIjb65S2GFDA9TSk+FxrLnoz9u
        K1Fnf7beO6sU0IFb0hykJ6rMwp+8MGEfuzBuUgGHmiBmMFaiseZk3A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-17T01:46:27Z"
  mac: ENC[AES256_GCM,data:XYnlZlJ8HKldjEKiYAQP5XcnKKsFnJM3p8j/uOq7Nps+N5BYZGpw8EwKwHLuIfnayoK3H0S+OYZ+TnK2KEIx8G1Ht7g9/GTU4abdzuX9W5PLYMGAUeN2nQ1hki6B8JcsSlrd1kGS2yEX72xGnycapER5cSKtskkCRXNecsljvv0=,iv:WWJ4bCT/dT+m3bYXoVxM+ubBqi3uGgHD5Y773H1L5KQ=,tag:+EO95teiN2g0pZC2YWqzRw==,type:str]
  version: 3.13.2
