apiVersion: v1
data:
  GATEWAY_KEY: ENC[AES256_GCM,data:aDO9HyyKukoPF/4cjfIfHNnCdJ9s7i9si2BT+kP6bb21PI7UKlYvC3DRcYRsi1oioFCbVMJZfnitjPMuXiXRY58YoeRggLt2A7p4AzDEGyiaPvFwhtzvjw==,iv:X5uzZ++2I9fkSKBay28Oi9TsHYqJTu0cbK1HDPC3mUw=,tag:2s9rhsIaO93P4L4LYDubMg==,type:str]
kind: Secret
metadata:
  name: eek-secret
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSUFqSjhvYVR0VzFKdTBZ
        MnIwNFlLV0JhWERsSUdqc2lJT1JUZ3RrNWhBCmx2V0RDamUyWFI4YlZCOCtHZmNW
        c2pVdkRUTmxVclVzQ2tGTllBbE1lWkkKLS0tIFVTZFRjaGhuT3NMVzl1QlozZWgy
        Uy9hTTFpM3FPeTJkeWozMWtka3pGZ28K+SVeQixfmJF/XvzOGCfUSFO0dfuFuUYi
        y3Yq1oyK6FTDKkMqCiAbNZVxZ0/MYpbmDbnJaGU914RCDDlSO+H1gQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-17T02:31:58Z"
  mac: ENC[AES256_GCM,data:2MMGXwkw9lidqMJzPyoUGLmTsOXDy/h8N0AYoP2+8q9DLVX2VMlV61CL6W4FHIybG4Uo+NZoyYuuT7f7aJPyhnEEXDt1u5lRlKXCG9RXdu/9+ZnpnZ03PLU2bWik0Doo9kjvwlgiDsQVksM7xRD6pk91qYbvboIB1CiATUbVhKs=,iv:Njsnzlm4EaaaiipoLuzRzC5AT2NGou3FFoGRpLNkBV8=,tag:uVdYDNA5mY+bzHLr0s0zsA==,type:str]
  version: 3.13.2
