apiVersion: v1
data:
  GATEWAY_KEY: ENC[AES256_GCM,data:vKDRb5lj8FkvA9S+EGqzUf03GPAsvpIoHI5aLh6wNMu4l/UM3JVTHMI5+ciilqXmGsMUZHqm0rS9IPrGMjjvp59EphhGMuIL5gXKq3X8pbzQcCSveLmijg==,iv:cztRAntranS805Z4OEFl8uPb25HyTujIAyMAudcvyhc=,tag:YxYN7AWH73JHOCkKmN6BBQ==,type:str]
kind: Secret
metadata:
  name: eek-secret
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNEQ4RmtLMEZWWjVodVY3
        ZTN1dk1Td0RLMGNVeGEzQ3pmM05vWUZPZlQ0CnNwWHorZzBCNUY2TzBkUFZhLzQ3
        QVR6VzlzU1JVbllNZzZLTGIxangvQUUKLS0tIG8zSHFvWmVnMTNMbERhVUJpWG5w
        aWV0dURIazl0WERRYTZPb3dENi9XNXMKG21EYQCLmaylR6VPYaLFey/hOVX1PVUK
        TSx5RlkKpRfgSyVIMrgyA9jlLWMV8RkOcGDuA4Thmx3PT/NP//TO6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-20T21:04:07Z"
  mac: ENC[AES256_GCM,data:0HDoDLYyueAyA2yQsQ6bXhTotLtIAkiTZOyVuNJp6Ym2XF0/09sEMIfjOBYhwzgDjuyhbXWshpiSFopH1nv+stDS/pJLEqK1MsSnkkL4wgIGVcQnC9z7hPl5Aw5Fbk00nVpklKYa0VPwBBzo/dUDajgjg4LIjs2EuXesE7a76kY=,iv:ISMOYTn6zrzY2WhikcfGSmAmXICRMvZqRxAu+Ju3LSw=,tag:m5j46X+jKqaSI+wkRHYAPw==,type:str]
  version: 3.13.2
