---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-role-atuin
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: postgres-role-atuin
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: atuin
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "d1f95550-a56b-4f5d-a3f9-b4df00f7fe4e"
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: atuin
spec:
  name: atuin
  owner: atuin
  cluster:
    name: postgres-1
  ensure: present
