---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-role-grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: postgres-role-grafana
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: grafana
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "f83be31b-e809-4a1c-961b-b4df00f8edce"
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: grafana
spec:
  name: grafana
  owner: grafana
  cluster:
    name: postgres-1
  ensure: present
