---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-role-immich
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: postgres-role-immich
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: immich
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "693a1b1a-c731-41b6-8a06-b4df00f6aaa1"
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
spec:
  name: immich
  owner: immich
  cluster:
    name: postgres-1
  ensure: present
  extensions:
    - name: vector
      ensure: present
      version: "0.8.6"
    - name: cube
      ensure: present
    - name: earthdistance
      ensure: present
      version: "1.2"
    - name: unaccent
      ensure: present
