---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-role-linkding
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: postgres-role-linkding
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: linkding
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "66282c8d-33c0-4e39-984f-b4df00f6ff0e"
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: linkding
spec:
  name: linkding
  owner: linkding
  cluster:
    name: postgres-1
  ensure: present
