---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-role-lldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: postgres-role-lldap
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: lldap_user
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "3c71867e-f081-47c7-a2cb-b3d50167f165"
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: lldap
spec:
  name: lldap
  owner: lldap_user
  cluster:
    name: postgres-1
  ensure: present
