---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-role-meet
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: postgres-role-meet
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: meet
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "608ca4b5-aff7-4e27-9305-b4df00f92d8a"
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: meet
spec:
  name: meet
  owner: meet
  cluster:
    name: postgres-1
  ensure: present
