---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-role-memos
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: postgres-role-memos
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: memos
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "ab9a3919-74bf-43d2-8db0-b4df00f73f30"
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: memos
spec:
  name: memos
  owner: memos
  cluster:
    name: postgres-1
  ensure: present
