---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-role-miniflux
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: postgres-role-miniflux
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: miniflux
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "c6ef0e97-2091-44ac-99c2-b4df00f7c083"
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: miniflux
spec:
  name: miniflux
  owner: miniflux
  cluster:
    name: postgres-1
  ensure: present
