---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-role-n8n
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: postgres-role-n8n
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: n8n
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "b42bb6ed-f5b0-4060-bc69-b4620120f318"
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: n8n
spec:
  name: n8n
  owner: n8n
  cluster:
    name: postgres-1
  ensure: present
