---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-role-pinepods
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: postgres-role-pinepods
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: pinepods
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "7bb9fb26-61fa-4010-ab95-b4df00f8a970"
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: pinepods
spec:
  name: pinepods
  owner: pinepods
  cluster:
    name: postgres-1
  ensure: present
