---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-1
spec:
  instances: 2
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6-standard-trixie@sha256:79be0d10e78b7ac4520cf6c5db199a8bb7f6de53b3229f47e90cab5865528a0d
  primaryUpdateStrategy: unsupervised
  storage:
    size: 128Gi
    storageClass: cluster-nvme
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        passwordSecret:
          name: postgres-role-immich
      - name: linkding
        ensure: present
        login: true
        passwordSecret:
          name: postgres-role-linkding
      - name: memos
        ensure: present
        login: true
        passwordSecret:
          name: postgres-role-memos
      - name: miniflux
        ensure: present
        login: true
        passwordSecret:
          name: postgres-role-miniflux
      - name: n8n
        ensure: present
        login: true
        passwordSecret:
          name: postgres-role-n8n
      - name: atuin
        ensure: present
        login: true
        passwordSecret:
          name: postgres-role-atuin
      - name: forgejo
        ensure: present
        login: true
        passwordSecret:
          name: postgres-role-forgejo
      - name: pinepods
        ensure: present
        login: true
        passwordSecret:
          name: postgres-role-pinepods
      - name: grafana
        ensure: present
        login: true
        passwordSecret:
          name: postgres-role-grafana
      - name: meet
        ensure: present
        login: true
        passwordSecret:
          name: postgres-role-meet
      - name: lldap_user
        ensure: present
        login: true
        passwordSecret:
          name: postgres-role-lldap
      - name: pocket
        ensure: present
        login: true
        passwordSecret:
          name: postgres-role-pocket-id
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 256MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: postgres-1-backup
#  extensions:
#    - name: vector
