---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: __APP__-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: __APP__-db-secret
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgres://__ROLE__:{{ .password }}@postgres-1-rw.database.svc.cluster.local:5432/__DB__?sslmode=require"
  data:
    - secretKey: password
      remoteRef:
        key: "__BW_ID__"
