# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: sonarr-secret
stringData:
  api_key: ENC[AES256_GCM,data:1Ofo46ZjJ83xbHhHlaAyuFqqlUKznbWfi26uDjst9uI2ZQ5KkmqEiQxk8Zw=,iv:s/IjFYJtEWDxh+HlPhI3ZMJ+N+G1A+ubPd2n3oVReQ8=,tag:Q5LY2w82k2Ns87mC683hTQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMU56cXVIbnRPVjUxNVBh
        amw4OXd2c1l0NHp5SWlNOG9IcGdMc0RWa0I0CnNpY3VGMllnZFZUdnVOS2ExT2Fz
        L0R2RmJ3V3VaNG5ZQ1FvOW9UNjl3NFEKLS0tIFAyd2RENjBrNVhCTFovMW5HZkxJ
        NVZheVRzU0lOTktxVWp6V0xyWmxYeU0KKANNdqM+Bgq+mjimXszlZcJwnPmvopg4
        HM3VNqy3x/OAqalIGGNe1uajBlP96PAjcQjINyRelxlzhIlpm7kVJA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-15T19:03:37Z"
  mac: ENC[AES256_GCM,data:1kG/MPKXFLNdRw8yshVNYizLhx9+RdtA+BYE7DXkUCRqkKnBA9WgIqkrWHvnCg+nqHydgYi5v2JN8BI3oL1dmTwazeBlxtYzQrbQeKQ/ObUvHBrNRJ4UNArJqDSGtg3I9mDE72hPAMgxLjZiCptIFF8bY+cmxACwyYZrFDFiNSc=,iv:64N1a7cs4Nqe1K/VT2OCiEgQhydV4lcT2T47ZA1MGlo=,tag:TSOe+tO1JJl4cXMcKNnQDA==,type:str]
  version: 3.13.2
