---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memos-db
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: memos-db-secret
    template:
      engineVersion: v2
      data:
        MEMOS_DSN: "postgresql://memos:{{ .password }}@postgres-1-rw.database.svc.cluster.local:5432/memos?sslmode=require"
  data:
    - secretKey: password
      remoteRef:
        key: "ab9a3919-74bf-43d2-8db0-b4df00f73f30"
