# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: memos-secret
stringData:
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:6UTRW9U=,iv:h91csZei+uPOfSSUqnTm55NyLQ+gEpqQwee2ZdBY050=,tag:ocUQUNwOHcnPS/Osu9Ot3A==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:7Me59qbowtVcXp50OHxfI4kds3OjXERwhHJhn0FfR2vgu696wg==,iv:QuaJvqixLoV+csFAYwidD4LnfCaOdFtEWawAWujLXGk=,tag:N4FZyRtoJTNYfVUS6y/qKQ==,type:str]
  MEMOS_DSN: ENC[AES256_GCM,data:kL7qVBzPALvNM5cdpHteHLzmibrwNGpJ9FymWJcTHQlYcjghSITuJfQ8JQjoT1J+gzkB5rhopmQFYrmuJSs/BkUdGAtAeYB3nZB9QseVlFcsz59ujG1qp33NB+iZKf978BPSpOpZEjZY3ot/VyugNt0piwS0AgwwnaT5Cw==,iv:go8DWD0bv0Wd9PHPFhcKETBZLPW7wmfBBOuVM8yk5j4=,tag:XC24VD5JdxaWlDXmwSlAug==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQUs1ajBOanJaK2xzK3Fx
        TkduVGF4MWRzRlUrUHN3bzhNZTZmY0hHUnc4CnAxaS9GUmVyaG8xa2d4RzFlMkhP
        bmNPNVNJSmE0NE42Y0tDVWY0WUNMb28KLS0tIG9XRGlyUlROelQrRytzZHo1SGVu
        T1VkZ3dQd1M3dlo4ZGlYK2F4UW5Za0UKpLP6aFOR3UApl+4P/Nv6wOIavPs5JErP
        jJCT7jY/A7s+5ow6VGarXuSwzbHa2cw0/6PHa84XTdsQmcisR6IV2w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T19:34:42Z"
  mac: ENC[AES256_GCM,data:FWf6qeNNEYuMzjmnxyR3lt6Jy6NkQ3hwPLycXdSMo4nFaBU8erB4DcH8GoOVMGSJdSQjArh5rExgZDDQwmDWCkmtPe6avLAQozgrfsYyZjXbYRnX6WgkVK9OB5SdQ31uUjrIAYgm8y3fQOrR76EZatjcPbShQQnnX0kHVR4ax9A=,iv:75Hoe+C0jvYRXO5uuwEX2xx7sOVA5rOkhtlOXbCBfAQ=,tag:sIwKtv+LJqRYfKaBQzkhjw==,type:str]
  version: 3.13.1
