# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: memos-secret
stringData:
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:21T+v70=,iv:4dx9BWo3xSwaQJV3XJQDnq49IkvoC7fbj93vXtEZvrw=,tag:HSmw7nth8fkU4YBP0lIagw==,type:str]
  MEMOS_DSN: ENC[AES256_GCM,data:FxYpN+M0rKkvZGkTBwjZl+9kdG04Yz2uA03IEZfBq/vEp440/1KJ+4q3d2sjLB3h878YGYYfLD+hkeZJ/9UYu1D9a7YPTpPo0gBhpFDU8/Sg7nH/R+b46rzkry729fxT+/uuU4eBwHEfgwF3aq+EyZea7L+p4E+Bf3B4yw==,iv:6N+5FXHoDFd16GS034J4VVYlLEKNE1VVj46FTUzdv9U=,tag:xQW0A2k+na7gTtmVhMIebw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NG80cmVKcmJLOHM0U3hG
        MDRmU0lkcEFYWDBzYTZ3ZHhaOU4vVjYrSWlzCllpaWlXNGk5b1VxS2tkcTNHa0dR
        aGJkRDlyNjJFU2NVem1EZ3VOR3lpZUUKLS0tIElER1k1NkFZTkY0L2phamgzQytZ
        WEN4SVBxRVU5Z3hBaDNHQTF3UGRtaE0Kyh1E4LokI31ILlNCDJc0IFxVpdH6XWtb
        xW2+oejiQC7PTREagfTh5E/obstOMNAVfSlypG36hNznE+cqUXhxdg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T15:07:53Z"
  mac: ENC[AES256_GCM,data:xTBUhZPz0dDvBPRVAuzCipwInEp5YpBx/ruZUxlyRcnlKklerve7zSk7pQDN5HUwePrVfcufekfzUkmC+J25BIJ8cVJdRz86EmAI2waGJssJIohCJiIaDmQR7VJ6hC6XzgyDQn0ZgCDJxcBslMfnYvEp0gn3NIrvnAHHZ91VAAw=,iv:x/I1Z1QeQSwmGq+0rhu6YGxm8521/x0dOij5FdxVI+o=,tag:9U4RMAMy4uIYXA1trt8EdA==,type:str]
  version: 3.13.3
