---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: immich-db-secret
    template:
      engineVersion: v2
      data:
        DB_USERNAME: immich
        DB_PASSWORD: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "693a1b1a-c731-41b6-8a06-b4df00f6aaa1"
