# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: immich-secret
stringData:
  #ENC[AES256_GCM,data:y/DXZSrIP5THcpfGrzTvO7CsE5RgZBQsUeKfGn6ybeD8HmuWLlj6QqouLlo=,iv:MzuvyVroO6/oWwWUMBMgrkGDSqq/UiDbwQwHvDD3PZA=,tag:DjMci0xNljYGPcvBF9ASaA==,type:comment]
  JWT_SECRET: ENC[AES256_GCM,data:AhzLS0N1eeUusXLwRGncP3ipHQfQXbfU+UV2EazOlvWepy73lXOtG4F4PSwt5eQP,iv:+BaSvf2KJHzLLSWZTvqqsk9htE3dIK/sjdpWHheXk2s=,tag:ISuPy3d/x05hoh92VVuodA==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:09IDU/Xp,iv:cyPVKm5ZUFZ/+HrqkSKEozikVe3dTDPQOWUwNSuHK1w=,tag:7OFTc4gdQVCix4ukb60q+g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZE00SlpOUStGTEpVZ1pS
        Szh5WnMrUEtJeUF5RUx5NTZpY29PVGhOU2l3CmhnN1E3bVZiNTVtRzRpSHFGSmJC
        dmIyeWRZYWRFNVMybFBIUVFpRmVGbVkKLS0tIC8wSWZ4cDBCQnV1RkZOaHpxQnJ6
        bTNvcXVGS2tXbHEwdEZHNlR6Y1FCNHMKog5RnqLZAGdgkz5+gOQWeTU9NDAOfgCd
        mwhjb++jWsffm3N6t+QEgf1Ld8w4fh4x9VTHEnKqXNMkiUIUCJ0Uzw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T15:07:53Z"
  mac: ENC[AES256_GCM,data:ux+3fs76UDgVpaf2yXLd0iYg/wPFa5tJVqIEYbDqYqiiPd5aNQyXkG6ErkWRzIADwOcdemJmfSLtHpt5fSVWtWffqR1BHD7iOXUEjIIJQN+zE4j2FSRMGWLapaxrzP1i3Hm/ZRNUyNEVPBOeFkzBcDX5CWTAFDaOzA1KHvwyDUk=,iv:lbRzOO85nw+6SNUe4mzygKSOiycrwW5snbKvgChByGk=,tag:mrtdg7rEybcLc71fjbainQ==,type:str]
  version: 3.13.3
