---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./networkpolicy.yaml
  - ./filebrowser/ks.yaml
  - ./claude-code/ks.yaml
  - ./codex/ks.yaml
  - ./eek/ks.yaml
  #- ./openclaw/ks.yaml
  - ./llama-cpp/ks.yaml
  #- ./mcp-nixos/ks.yaml
  - ./open-webui/ks.yaml
  #- ./qdrant-mcp/ks.yaml
