kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: continuwuity-secret
stringData:
  CONTINUWUITY_REGISTRATION_TOKEN: ENC[AES256_GCM,data:lGR5ks3MgUTRSItysMu3LYMfEobwiC+ADlcNaQ==,iv:rJDQCH5kbmy9VToQnuNpdlM9P2FYx5o5jYWoipb0p8I=,tag:ylRBiP3QoBBvOs7/k7NxSw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaThzY3d5ZzhrNlgzUGpL
        ZDdVbWtEQVozRXBMWjFiSmQ2b09BOXpUaDBzCkVZbUtDVEtQSFJBUlBXMStvQkJi
        enNVMTJYYzVEMVRyRGdPeXo0QXFLZUUKLS0tIGVMQTJQQ3JrUFlIOUpCT0ZYTlZ0
        dkxkUzV6aC9YeWFobU4rTGsxV3c3SmsKICF5Ai0u0mGK188jywXrEt+jzwU9oymN
        bu5j2njsaGfBdwBSu/oXpoRcIHX5TvGLBuCzRaJM1SXYYbfM4OPJ6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T15:32:09Z"
  mac: ENC[AES256_GCM,data:uOfL98/B+gcJMO0A6pbfeULsIA2reC172N9Fq1Ov4NFXaAVGdVlR1Vytxircv2zy7Q4G8NofO0ZKMCa6dxUoo2p4W7SOhKKvTYfcy/3SVtW5WN9rhA16q6/SFt3/w+ICxeTwEslbuYnhSlul/U+SdZNMLKWt7FK9HOgfRdo3974=,iv:yMpsPqlVVWErz5nUZfvrMGDznovxJH4iWDc0cG4BrPc=,tag:5oRJbzzp1F66w4xFVmqwAw==,type:str]
  version: 3.13.3
