---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: pocket-id-secret
    template:
      engineVersion: v2
      data:
        POCKET_ID_POSTGRES_USER: "{{ .POCKET_ID_POSTGRES_USER }}"
        POCKET_ID_POSTGRES_PASSWORD: "{{ .POCKET_ID_POSTGRES_PASSWORD }}"
        DB_CONNECTION_STRING: "postgres://{{ .POCKET_ID_POSTGRES_USER }}:{{ .POCKET_ID_POSTGRES_PASSWORD }}@postgres-1-rw.database.svc.cluster.local:5432/pocket-id?sslmode=disable"
  data:
    - secretKey: POCKET_ID_POSTGRES_USER
      remoteRef:
        key: "d5162a26-79ad-4f8a-bbd5-b45301722b82"
    - secretKey: POCKET_ID_POSTGRES_PASSWORD
      remoteRef:
        key: "01f2bef3-dd9b-453c-afd8-b4530172496f"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-encryption
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: pocket-id-encryption-secret
    template:
      engineVersion: v2
      data:
        ENCRYPTION_KEY: "{{ .POCKET_ID_ENCRYPTION_KEY }}"
  data:
    - secretKey: POCKET_ID_ENCRYPTION_KEY
      remoteRef:
        key: "179dc77d-e3bb-49a8-9445-b453017264b3"
