apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:s/jZyv2CdLKxsfD/j4nS,iv:ozIhFNWAaFJ0OFxoDTVFS9EnefSF8ju4ZYHt9ySQvhQ=,tag:jwKXEAqopNkOrZeZTT/KEg==,type:str]
  SECRET_ADMIN_EMAIL: ENC[AES256_GCM,data:0L7kTa9eFVZrzlB/qVeW1g==,iv:Jm9D8uhMGgipeMpM6w0V1YDEDBHN8kJA3qtUVYON9YA=,tag:fy/MPmTGGtUYfkj1wljgrg==,type:str]
  LAB_DOMAIN: ENC[AES256_GCM,data:6xbcFgggbrEe0Rk4yVFH,iv:qgTgBW7rJ8WDVuLcjul6OPwClEQEWISFnSRw5MLI4Jk=,tag:0Cc1QXstaHVFUrbEsU2kgQ==,type:str]
  PERSONAL_DOMAIN: ENC[AES256_GCM,data:6kXqGgb7QX8y7g==,iv:/S8/guQ+lDMZqvfUdSb0uBpvoxW9gzd84H1rQlbJ4TA=,tag:QwnqSzPmbirQP0QGvfU1oQ==,type:str]
  ORG_DOMAIN: ENC[AES256_GCM,data:hOEgdQ+/UuNa91bC,iv:muTPixQQPQRMcpVNmetJm5HXRzgQF7PBjXmDoO+P9NE=,tag:lfsNIvKpZkemoDqn/jbhrA==,type:str]
  SECRET_SMTP_FROM: ENC[AES256_GCM,data:qlSGZ3X+DhKGqj4+E73ZGX72PDzVnGAacc0zf8w=,iv:wvPbvPlQry9psKWBEZp0W896t1yQgRzXA7cvJWfp7/0=,tag:0bEiDL3uOfgpbj7pbXz0Cg==,type:str]
  SECRET_SMTP_HOST: ENC[AES256_GCM,data:jbxw8HNI1/OwMwi7n2Q/UA==,iv:2PFykZj78rgMokH0WoFmpNMsJyiKdIXxHojs/zTArdU=,tag:57FM9sYLugy7uazsCWXbQw==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:6RGZGUB1RU/CY4x+53LxMB6I5ztysW7VP0e3cHu4pm41SHt6,iv:vmVKkVjcMlYF2xF0rcyq2WWnke6JWL+QD0LxqeIY+D0=,tag:+AFHSPbU1gEWyUv4WnhqKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1T1Z4ZzBHa2VwTGdrRTZT
        TWpIdGY1amFvaGJhVklDME5qUzFrZ0p1T200CnBXVjc4YmNnTVNlVnRiOXp1NGVx
        KzBBaEV0L1BVcG91by9vV2plR3lnMXMKLS0tIElIWU41MlNwNjlYMTFhSThDdFV5
        V2syRG1TdS9odlYzVHNsdE51NlRnV0EKmsoz0Rnrcn3Z7QQlTyarg28r99652kx8
        5l+9h6KFsr0XBTrhmUC5vmcOaC7bVsi72DsfcumtpQ30mKnsNr8Yhw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-08T13:06:44Z"
  mac: ENC[AES256_GCM,data:scBHtJ3adqXLRkOuvckMKbnFduqHrgeCI463D7Mg47CdDDfF9IiIK2uMoW+kpbm1Uv1Pw/WOVqgMjjQ5ShMd+eVvxUzsJxj1P66t055rnM7ohuCpdObyZBw032K34nrcYSJ4RxzDjdb98srsnLnV6hBdg+WYMQtkYVKsiaNSE54=,iv:K1mybYT3362w/3HLwt3Hj5xQdoW4qjTC1+SU20ffoyg=,tag:UJdl0MkdGE/X9wKyBBkTxw==,type:str]
  version: 3.13.1
