apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:qGfJW6Sv223tk2DvBL0+,iv:eeKafoNjP3h8SH5QP9eidzyA1nfydutC8CP0CJMAZw0=,tag:+1uKttdGZBrjjH0FVnpvBg==,type:str]
  SECRET_ADMIN_EMAIL: ENC[AES256_GCM,data:DAItVVroGpRdkTjocxO34Q==,iv:XEmFx1LNiQt4ZfvYW2CZfe5r6SoGfvXmcznpiv6fuKs=,tag:Nxwat2wn3jPvGxOlAyLhOA==,type:str]
  LAB_DOMAIN: ENC[AES256_GCM,data:+ht8i6NGkvUBLtmgzhub,iv:qU4GqJ8QqNyJckt7KPl0kLkFYAkV5Ip9BOM/On+sLcU=,tag:IFzCCekN6OZ/piSx1pppJw==,type:str]
  PERSONAL_DOMAIN: ENC[AES256_GCM,data:S8SC2gITUx7T3g==,iv:U5RZDabS79S87X6YBMa/R0WPsv39l/s8OXsGV0fPOj8=,tag:dt6I9BwFWU4wuu8hRHhwKA==,type:str]
  ORG_DOMAIN: ENC[AES256_GCM,data:H413doMXoWYANp/B,iv:d5qIL8Ne7x7PCU8NTOHSZZrKwEWmfW1n/+wMM5DHnkc=,tag:cO18SGiVRcTmL3qkFOv+5g==,type:str]
  SECRET_SMTP_FROM: ENC[AES256_GCM,data:YgTOKnBg1cUZqIDrWfK4qNrLjNZ0qcObF2+1t4Y=,iv:HDy0uen1fKnxaGS9bLL4hG9CdBBOzjc4zuCSpB0PNH8=,tag:Tol/PkWP1GexbPW/Lf4GDA==,type:str]
  SECRET_SMTP_HOST: ENC[AES256_GCM,data:eod8panzle3WbHbwsXcUjw==,iv:W9NulWGV8QbesBvgaj2vWhVzpVcdSpA3s1D/b0lo6CE=,tag:ctYQYK+jzVmskrA7ew77Ng==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:zrbWKdreYM6ir/Hm0a02JpJvQ8qo0zOMWZDFL2PhdJzxOtYq,iv:tPc2WQg/5Z6xsxNSs1vNUlRq3cQV0j/jz+cFdh5OnUA=,tag:FzPAY/XPP//J4J67zqSXrw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U2Vwd2hCWHJ3RVluejJz
        MkhSd0NXOUN5dzhEdFkxYmVyUDhTOUFnNjJvCjlGOUxTeERuUm5QVDI0dHludXhu
        SDJrbWtPb0dkbmw0dUIrR0lBMU1Kak0KLS0tIG9rdUg0SHBSYXJFRHFrYVJ6VFE3
        T3FMbm9mZG9HTmlxTVBKdno5aDR3RGcKMudlAzjnguH/8addZUmn+2onHLf+g6Cu
        qisYxnqeNm24CEriQrY3dSjTa4VgFxbjtDgkWTghOWOx4mU5iL/8Cw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-09T12:46:49Z"
  mac: ENC[AES256_GCM,data:tqye7BiwIx7kjFDE/oSsMjerr/MwOWDfRlLzc2T2ej9mZ9MQ+mLD1I/pwbl6279IlSgx9XuOGzvGVNjOVv2Xf31+kVx3PBLq4PIyaccOtBDSfDm+XW+h/dy8MkVzArbHO6IElhHkr9OPVSu53S5zv2zKZH/t/yC+pCigXcGOUz4=,iv:XuUZgk5LcPiI4SSHdm/55zKwM49fE8FbgQXS/6CToxo=,tag:xcW2U6M29VMHkfbaiVjMYg==,type:str]
  version: 3.13.1
