---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-media
spec:
  capacity:
    storage: 1Ti
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: media
    name: media
  nfs:
    server: ${M1_HOST}
    path: /tank/cluster/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeName: media-media
