---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app renovate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: renovate-secret
    template:
      engineVersion: v2
      data:
        RENOVATE_TOKEN: "{{ .RENOVATE_TOKEN }}"
        GITHUB_COM_TOKEN: "{{ .GITHUB_COM_TOKEN }}"
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: "83946237-f995-46a3-90da-b468017dcbe9"
    - secretKey: GITHUB_COM_TOKEN
      remoteRef:
        key: "4d5ef864-5487-4e6b-9ae8-b468017ef7ed"
