---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app traefik-vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 41.2.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    deployment:
      enabled: true
      replicas: 1
    service:
      annotations:
        lbipam.cilium.io/ips: "${LB_TRAEFIK_VPN}"
    env:
      - name: TZ
        value: "${TIMEZONE}"
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: traefik-vpn
    ingressRoute:
      dashboard:
        enabled: false
    additionalArguments:
      - "--entrypoints.web.transport.respondingTimeouts.readTimeout=0"
      - "--entrypoints.websecure.transport.respondingTimeouts.readTimeout=0"
    ports:
      traefik:
        expose:
          default: false
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
      websecure:
        asDefault: true
        http:
          middlewares:
            - networking-traefik-middleware-secure-headers@kubernetescrd
        transport:
          respondingTimeouts:
            readTimeout: 0
        http3:
          enabled: true
      metrics:
        expose:
          default: false
    metrics:
      prometheus:
        entryPoint: metrics
        addRoutersLabels: true
        service:
          enabled: true
        serviceMonitor:
          enabled: true
    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: *app
      kubernetesIngress:
        enabled: true
        ingressClass: *app
        publishedService:
          enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi
