---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: atuin-db-secret
    template:
      engineVersion: v2
      data:
        ATUIN_DB_URI: "postgres://atuin:{{ .password }}@postgres-1-rw.database.svc.cluster.local:5432/atuin?sslmode=require"
  data:
    - secretKey: password
      remoteRef:
        key: "d1f95550-a56b-4f5d-a3f9-b4df00f7fe4e"
