# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: atuin-secret
stringData:
  ATUIN_DB_URI: ENC[AES256_GCM,data:uf0o+CAiPPc5HHjw1A+/oSiR794hQzKiYf5kH3X4tx2+dougI8qzahFtGJzD+HH3rrbdXs3xDNaIcf2potkZYD4/vpYoTtOOUnoRxil6pG4ZEZ20JQYbEQ==,iv:ccjAFr0Xz+OigbNpbp+KCTRPq4MeZPyw8Km2k3nHzM4=,tag:4Z9K1uSoRJXpYp298zGbyg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:OqjvX3E=,iv:twv+0PZoroEt+Xuap2Oi2zekBJUDM677zGnyTqw3WCA=,tag:vEUZB0/nqVK3P47l7hpbXA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeE9EcFRWWis2a0VKRCs2
        Rk5PR3NBTGU1T2ZFcitvcEk5V2NQanJwdEhBCmNMR3p0enpFQnkxVkN6UURVK3Q1
        aEpSVU4xYVhPdXdITTRRTkJCV2lJOHcKLS0tIGtzc1d5MThqTHdXN20wQ0hOcEdm
        bjlubEFHUnM5bVR5Qkpyb3lZdEo4NE0K01syDYhdZdDdpsR3Ofs23e4CfvIA1/6c
        NoslSlBwVKhdgKS/dr/2JftIiQOuHFYUa/xj+ofcB2Se4yva3RYmJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T15:07:53Z"
  mac: ENC[AES256_GCM,data:u855/DSuO0RWJGZYYw4XS0sPFGhHYtBcCnu4vpkYJSrrjWlVKGr5OyWFbNJXC9M+xsOunNMoRvdrSr+ek0Dtg60PonWxqKw902kYjpLF/8uQcqP3wdhB7MteRaaCWGHDPGXsRput/valnb93GrmwRcooJ5ScygGBzKc/Peika+A=,iv:07mIwVOALtZqJeuDOLbaJsXMDxhLjwaNLaMdjKqchjo=,tag:koLRsP2UWdAm87oZ8lzmZA==,type:str]
  version: 3.13.3
