---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app opengist
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: opengist-secret
    template:
      engineVersion: v2
      data:
        OG_SECRET_KEY: "{{ .OG_SECRET_KEY }}"
  data:
    - secretKey: OG_SECRET_KEY
      remoteRef:
        key: "68655143-02b3-417e-b071-b462011e7822"
