---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./networkpolicy.yaml
  - ./continuwuity-org/ks.yaml
  - ./continuwuity-personal/ks.yaml
  - ./cinny/ks.yaml
