kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: continuwuity-personal-secret
stringData:
  CONTINUWUITY_REGISTRATION_TOKEN: ENC[AES256_GCM,data:8x4RpmfvusBTwdpYI2bhjTznvYqI60IzQ1i/bc3zlsI=,iv:VHJOrd+fhWuDRkweougjOVRMtRoJ5sqqS0/o8lW04Fw=,tag:o0OYHtcL+25HynfQIwuIgA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTkNyRWx3KzNSL25PVVJO
        U0JFVkJwZVJLZDN4TCt5ZVhjN0FzbS9va0JvCjNVMHo4cXIwQVdJcDlyS2JZTWRn
        L1ZFTm9rWXlLNDlnTW9VUGRQU1Vud2cKLS0tIHZOV3gzM1RDQTZOUWFOUTZQb2l5
        R1VsUnp1b3JwZXRtYWh0V0RveVh6d00KOnGGUlrZX4sZr+6LerU3zRCSDp2uHYvx
        zeVWQciS1F/3Qx/I7uPb7i0UM5wuCWMeETzgDBuZ2PgHZqMJMHnBbg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T19:01:54Z"
  mac: ENC[AES256_GCM,data:1ISqsSTQNW2XCfXWbSMmrevPuP8it9+LsOtTG6OCWfHmyRIFUq4MQVxz7rm+WXp/sRpGLeqVf8QrnkuLTyWFfHYYKTtBDiTUHBVT9naEdFO9Mu2X5vzBX2SHrEaMMqbgEclg981DeHKkR7+nE8irbIAN7ZUP80zqLdmfB4CtbuQ=,iv:MaIUFNthH1AfUKf/ojyES8uVFz1MP9tH2dYmsMZjIV8=,tag:7kE/mWFoxLhy2Fc15PxomQ==,type:str]
  version: 3.13.3
