---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app netshoot
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      app:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/nicolaka/netshoot
              tag: latest
            command: ["iperf3"]
            args: ["-s", "-p", "5201"]
            env:
              TZ: "${TIMEZONE}"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 5201
                  initialDelaySeconds: 0
                  periodSeconds: 30
                  failureThreshold: 3
            securityContext:
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
    service:
      app:
        controller: app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "${LB_IPERF3}"
        externalTrafficPolicy: Local
        ports:
          iperf-tcp:
            port: *port
            protocol: TCP
          iperf-udp:
            port: 5201
            protocol: UDP
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }
