---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: linkding-oidc-secret
    template:
      engineVersion: v2
      data:
        OIDC_RP_CLIENT_SECRET: "{{ .OAUTH_CLIENT_LINKDING }}"
  data:
    - secretKey: OAUTH_CLIENT_LINKDING
      remoteRef:
        key: "624a05ca-363b-4cbc-ac68-b48500f94f0c"
