# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: alertmanager-ntfy-secret
stringData:
  token: ENC[AES256_GCM,data:7wvc1kNIzJuqh1rgNWhEqxIsRl3pkEggLzolwwKk96s=,iv:jIA7dsUhE1ykoZeLPqX8UxoO3bWJxD4p0/QNPvje8N4=,tag:aI2hC4Xp6BZ/D4nnAnRb5A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaclIvcFV5ZlJjV3FRM3JD
        bncxdlJaL09zeVFBcTl2TkRoOHRGaVJvcVFvCkVFSVlLZFJpUWV0ZDRkaHd6STA0
        ZzZqZHFKRjcxSDFtbWM1K2IrdFZrbzQKLS0tIFI3RkFYclppakxhdGlEeWZFdmRm
        UGNBRUNuSjhEMTlwRlBzT3JlWXRDQWMKQFTGp0wBfSswuCdQ1zm0sd1EWHysvBoo
        ZmA2/oCGG8rVL5NxeSzz1zY3z2D9c3UHQbzlW+Ju4xeH9IjdZYOwYw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-26T00:43:39Z"
  mac: ENC[AES256_GCM,data:7yNhUsg+2yNpEnWHqkhscBz3x/TN8RrzJv0f0ur1/aVV2k8rA72t8wjU8OdPlPoTHn7s/azh6uWWsr8MAMOJhDhseI++Zo69q29YgV6kKVDvZoDHX7qez1eg7k7V01UTBtgxV53qe099Scyqki30sQwNiOHlGp3//WW2XwlPeZM=,iv:YAbY5CdVPrEf3Q4JC2lylTaBajYjrDu7pJjfRd9Rih8=,tag:zT3eA09Gjq0ZGHqauVBuTw==,type:str]
  version: 3.13.3
