---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: forgejo-db-secret
    template:
      engineVersion: v2
      data:
        FORGEJO__database__PASSWD: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "2b97cb3d-61a4-4193-92fb-b4df00f84c99"
