---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/volsync
resources:
  - ./ocirepository.yaml
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./networkpolicy.yaml
  - ./ingressroutetcp.yaml
  - ../../../database/cloudnative-pg/app/secret.sops.yaml
patches:
  - target:
      group: volsync.backube
      version: v1alpha1
      kind: ReplicationSource
    patch: |
      - op: replace
        path: /spec/trigger/schedule
        value: "30 */6 * * *"
