apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secret
type: Opaque
stringData:
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:1rlrfJ5IZQ==,iv:ocKeR6SuuFNd4IAXb8RHzOO6iouL234ZrACW6Dk+294=,tag:VDIJfkc8RtI3ojBlh2IBuw==,type:str]
  FORGEJO__security__SECRET_KEY: ENC[AES256_GCM,data:ll4182sGRgiZK4d/dG47AVcixbK21gRMc3b0iQjyzE0I6PIvSEMse2oTI8On2bIXC2V0ofikeG3M+kw6F/hKgg==,iv:H0OHqhypeWCe4dLjqeLiut+A3x/5wdnGzJtp4KTgJ6w=,tag:jlinUKVAhMp66S1yZ830SA==,type:str]
  FORGEJO__security__INTERNAL_TOKEN: ENC[AES256_GCM,data:RLflkHozYSjL3sm1YW1i8k7HIXifyYXm1XSR+ThX9w+hjKxt39vKJmZ0T/LzuXevWWspZrtoeDlFtDty5wlyBBKj9d0oY1iNtD8xBkMesgUl5MmjtEPAmOqYBcATpfCg3skHA69vToCzpWcJqzlVTtM92drIsP3KmwGTmMbRRO4=,iv:VpfeCdwTjuGjFWyX7kEpBDYVZs9V0bXTmtjuMGm9718=,tag:NKQeUIKkq3LzUOlcIs4J7Q==,type:str]
  FORGEJO__oauth2__JWT_SECRET: ENC[AES256_GCM,data:cflEkvMUmIBs3/+w1sT03GFEFotjd92DeDIjFxQMK5qxkeoybQ8LiCf+Lg==,iv:VKIXgzluF+zHJ7DaHLZzyTOZLlSEYrV81uqywHXgRmc=,tag:g3txEevUkQ4YfWapEzelmw==,type:str]
  FORGEJO__server__LFS_JWT_SECRET: ENC[AES256_GCM,data:WSMc4AG6xY6DZLAhcNGTvJf/QIU0ugN1RjQyAxaXxC8bzhFMDRModKva3A==,iv:3PNpkcmkafhkRz/AAGQFKTKCUNrVjuRYkncIZH6Bk0c=,tag:NVzTnZcoHe1u4G3UYOKRxw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eUlIVTZaRzY3Z2JzY1Nz
        ZlZOUWRWMkhPdnpmSWNEU1RvRGNyRldQTVZZCjZKMldxbWFxeXcxa1RDaFFRdS9O
        SHBmY0lDaXI1bnlEMm0vZmVuUE1Gc0kKLS0tIHBPRk4wNlFoYVZtVnFIK1ZLaFRo
        TFBDdkdycGtXWXFnSjFsak53MlBZY28Kzi4MMUpSNgNVJFBB78bJC8+i4uhFyMHO
        ncK3x/nIGTZ9VnX2qSUXVo0ZtL+F7d+qbjkHvYyS/hf3fmP9gA0jrA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T15:07:53Z"
  mac: ENC[AES256_GCM,data:1QexIpRjn4/yt6Acxl9qkeFcT6jM0JE8gGwEECuPpU/KSZBLe7pk/O7SvhwD3ww5nCNj1B1SgNJXYdCwq+CgDOWf5N9URUtJnvzAytIwQzRNrSPCw/Ad0wyo2hiGxr09Z4r42oZ06MPQXqiETAOPOU+iHhdhnrA9YcOugYtn76w=,iv:d7u1PvKuIgtkWPENrNCk7eR92n96aC0LroRf4S3qzIs=,tag:9BoOUFFgDC9+nsH4g4/30w==,type:str]
  version: 3.13.3
