---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app n8n
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: n8n-secret
    template:
      engineVersion: v2
      data:
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"
        DB_POSTGRESDB_USER: "{{ .DB_POSTGRESDB_USER }}"
        DB_POSTGRESDB_PASSWORD: "{{ .DB_POSTGRESDB_PASSWORD }}"
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: "9f1bae6c-2c69-4470-a35f-b4620120a3fd"
    - secretKey: DB_POSTGRESDB_USER
      remoteRef:
        key: "1b085ec2-06e8-436d-aab8-b4620120cfed"
    - secretKey: DB_POSTGRESDB_PASSWORD
      remoteRef:
        key: "b42bb6ed-f5b0-4060-bc69-b4620120f318"
