---
ingress:
  - hostname: "${PERSONAL_DOMAIN}"
    service: https://traefik-external.networking.svc.cluster.local:443
    originRequest:
      http2Origin: true
      originServerName: "external.${PERSONAL_DOMAIN}"
  - hostname: "*.${PERSONAL_DOMAIN}"
    service: https://traefik-external.networking.svc.cluster.local:443
    originRequest:
      http2Origin: true
      originServerName: "external.${PERSONAL_DOMAIN}"
  - hostname: "photos.${ORG_DOMAIN}"
    service: https://traefik-external.networking.svc.cluster.local:443
    originRequest:
      http2Origin: true
      originServerName: "external.${PERSONAL_DOMAIN}"
  - service: http_status:404
