---
# https://docs.cilium.io/en/latest/network/l2-announcements
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  loadBalancerIPs: true
  externalIPs: true
  serviceSelector:
    matchExpressions:
      - key: app.kubernetes.io/service
        operator: NotIn
        values: ["syncthing-sync"]
      - key: app.kubernetes.io/instance
        operator: NotIn
        values: ["traefik-external-networking"]
---
# announce from n2 only
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy-syncthing
spec:
  loadBalancerIPs: true
  serviceSelector:
    matchLabels:
      app.kubernetes.io/service: syncthing-sync
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: n2
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy-traefik-external
spec:
  loadBalancerIPs: true
  serviceSelector:
    matchLabels:
      app.kubernetes.io/instance: traefik-external-networking
  nodeSelector:
    matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values: ["n1", "n2"]
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: l2-pool
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - start: 172.16.5.10
      stop: 172.16.5.254
