---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-tinyauth
spec:
  forwardAuth:
    address: http://tinyauth.security.svc.cluster.local:3000/api/auth/traefik
    trustForwardHeader: true
    maxResponseBodySize: 1048576
    authResponseHeaders:
      - Remote-User
      - Remote-Name
      - Remote-Email
      - Remote-Groups
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-tinyauth
spec:
  chain:
    middlewares:
      - name: networking-traefik-middleware-secure-headers@kubernetescrd
      - name: networking-traefik-middleware-compress@kubernetescrd
      - name: networking-traefik-middleware-anubis@kubernetescrd
      - name: networking-traefik-middleware-tinyauth@kubernetescrd
