# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: minecraft-secret
stringData:
  OPS: ENC[AES256_GCM,data:oe4GwK7EsjAaxh8dspI=,iv:4yhCTflOG7QKqAhdhhAfPeKaxU5xIw86r/fAT97/lY0=,tag:49fWYtBX2VDlSUs0qK1ijw==,type:str]
  WHITELIST: ENC[AES256_GCM,data:a7fi7RAV3n+EU+b+z3E0XxEPQUA5xm8hemnKkTidNY8NvtvmJsrttoVA,iv:KSxJhkXL4VhOa4DtaAWGZqH1K3rvcweJBdJ0gIcLvlc=,tag:BR00GziHAivHf2f1ta04aA==,type:str]
  RCON_PASSWORD: ENC[AES256_GCM,data:pZFX6sto5y8Qp/tIEBJ9BIeyj8saGOcM,iv:1v0+f+7mbrmBS6SRV6t4bgbQvjNlwp2MibcVm76Fn4g=,tag:A/OrAyPP0kdJvQsVRhKzgg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN3BzeURteGM5QTUxRTVT
        WEdtaHhaMmRJUHlDN2Q4d3dBNlp3TnNlendFCnQ0anZxQzUxNGQ5L3hoYlQzNUg3
        UFNITm1PTkMybkdEZitma3MvdEZacE0KLS0tIFZid1Foa1p0M1l6YnpKeTlwY1No
        WitXMElRRm9VV1Zta2ZSUGVDU3BwYnMKS0WAbloKBnwi1yJwHWnMlbNt2iv7ffg0
        1ZjnsbFUGOIZUBkN9MEykOiY1tAGshv6nkjT5ExiHM+I2tMx/s/Vsg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T23:14:08Z"
  mac: ENC[AES256_GCM,data:O5ZpRJMh8OtZH32QO1KpxSFEfvVTpiPAkchYe1gsijSKg5Ca+HESQjtXUSAVubx/hhdoyClfcd4eXcdGWCU8dfL2yn1cJCFNWVt7uePZuu2ShuyFZrszvhygxHMX3Xw2KO0IvCvwEjKv4JUzht+YUieZg7RhRG5S9wramyxbmV0=,iv:+DpFUIC9uAVMdqfGb88l/3Ks3E0qX5L5Q5K0MxrZph4=,tag:f4fV/bE1xuPveUvv7jACjw==,type:str]
  version: 3.13.3
