# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: minecraft-secret
stringData:
  OPS: ENC[AES256_GCM,data:Mo+aYaHZBkEw9eC33D0=,iv:RCwBTpr1o3HsI/E0N9ddclVVuq3F2ao77BRTg62cCsQ=,tag:R4QbMUROhM/smk4rSAo51g==,type:str]
  WHITELIST: ENC[AES256_GCM,data:qBO144BCW0abY/m6ydTMHJ0I09S0JJXrjTpz/ltp,iv:fXVvCUteUawtDfxzpeU8LrNxuZi+517S52rPtp9K5+E=,tag:ZD852cjBV7o5IaDPclnLfw==,type:str]
  RCON_PASSWORD: ENC[AES256_GCM,data:JnvH8rAxbikvVDTFgv145lz42y4+wcxcMoCgRvEH2swvwASNY//MfkjnbWkymB+p,iv:87O7xWP1en+hT6CD8fj6EPRmFRJr1YoQNNOdfOQQvxI=,tag:kJApTMLk0rcqAdV7Lz0aWg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Z0RCamNrbUdPdVNWd0JV
        UXVPZVdtbk0yUkRGWFJYTUU4S1luUmRGYUVBClYrbFh3TllmNXNQUnltL2lEOHFY
        NTV1MmlaSkNvUVVLTG5IcWhiaWV1UkEKLS0tIGorY2I5aWV4UC8wRzR1UTNNT1k0
        cHJkSGhBa080M3g3STgwY0tVRmFjcjAKzunDh2AHiCZQaDcsncOWcY/YjgYIO/+c
        Gciz7WouZzsPcUs2bvGyG9Llc2QU5L32Nhbnb/WEJ6WzWEmZ53Bi/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T23:19:44Z"
  mac: ENC[AES256_GCM,data:SLlCK3F3+uLDidaAylSrWXvW3B5i74TzFKqE13uX1tghEjLQpKlHwUAAOffs2joz04J+2eeJgG/ePZf/k2KrG/83rRUbtxoWYxn/EZ2QxMYJJt5Jdg8imt/+qW3gPub6+mzftKvn5o2OkzyMTPx5HZpINBf0xFmfnXl8SY/gPkU=,iv:hGkqyv3ECosoLpNoEo7B09mJGnJSGN3XatuaAiv8bbo=,tag:1xdeDhLqTNOEOPfRUzoiLw==,type:str]
  version: 3.13.3
