# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: minecraft-secret
stringData:
  OPS: ENC[AES256_GCM,data:CyRqhNsz/iX5diIb7Thi17KH,iv:idLkG46BRra5BsPP/xaR2q+5odlVtNIOiEVfLNIo0rg=,tag:8WBFDBRbq2+TEjbnJAqCQg==,type:str]
  WHITELIST: ENC[AES256_GCM,data:k47FT/5Ie74h0g+G0EzqSCxZBxDC/RX43ayeLpKzwcwB9WF1lBnPKcj/,iv:IHycXwXvRE8B6pOJwx+uwtNTDLddJq5zFH/LPR38ifk=,tag:XpJCFpyyblt0NCecmG5djg==,type:str]
  RCON_PASSWORD: ENC[AES256_GCM,data:3qjgZjRrwrEj8AiAMw9XUwTeuswy3SQ7,iv:odDV5LigZf0h98qpPyLKX2sD8RJ0rWnpF/6WFtI2OM0=,tag:WzkvqzPD/wZ+gvdsOZgTtA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TmpkRG9RM2psU0VJdlNK
        WWNYeTY3U3pmSHg0a2RYUXlrZUh4TUVIREJ3ClRxeEg4akN6S3Q5UnlsVE5ha0Nv
        NTlENWsrZEZpMVNNTlRMSjdhSmd6cncKLS0tIDhjNUpFM3dBNU9YNjNrdmJRQVhh
        RmpvU0pZVFJMV0dJRWVrZjladzRzQTQKuke0YEo5ib13A3wxmRS83ZcOV7ZHJE2R
        sZvAvzW+DaEKcgpL1/M9pT9vO6fKVrU2e++MvET+7Qmg6OT6ovctsA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T18:36:30Z"
  mac: ENC[AES256_GCM,data:d0+trzqAuhNuR0mEiWu6cN3+YH0+aOPEA+eVIWNZFuSzySMw+yQ9/u0u+Tg4i1ZdblreQKIPW3hG0wP/H28KBdbMVRx0KT0WRp4wA88NmU49DNdxIdozxOkDiQ4R7lB4iYucw7sry2tAcVslsmZXys4wSpZPYCeZJwzzTciVCx4=,iv:AwsUS8MFIg6Q6apb/7T04K4xf9J3Sx/cljdkk9psuGc=,tag:mmd9Gujld6UX5R9NauRyhA==,type:str]
  version: 3.13.3
