---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-no-auth
spec:
  chain:
    middlewares:
      - name: traefik-middleware-secure-headers
      - name: traefik-middleware-compress
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-no-auth-anubis
spec:
  chain:
    middlewares:
      - name: traefik-middleware-secure-headers
      - name: traefik-middleware-compress
      - name: traefik-middleware-anubis
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-no-auth-anubis-org
spec:
  chain:
    middlewares:
      - name: traefik-middleware-secure-headers
      - name: traefik-middleware-compress
      - name: traefik-middleware-anubis-org
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-no-compress
spec:
  chain:
    middlewares:
      - name: traefik-middleware-secure-headers
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-authentik
spec:
  chain:
    middlewares:
      - name: traefik-middleware-secure-headers
      - name: traefik-middleware-compress
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-hugo
spec:
  chain:
    middlewares:
      - name: traefik-middleware-secure-headers-hugo
      - name: traefik-middleware-compress
      - name: traefik-middleware-anubis
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-hugo-org
spec:
  chain:
    middlewares:
      - name: traefik-middleware-secure-headers-hugo
      - name: traefik-middleware-compress
      - name: traefik-middleware-anubis-org
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-shlink
spec:
  chain:
    middlewares:
      - name: traefik-middleware-secure-headers-shlink
      - name: traefik-middleware-compress
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-matrix
spec:
  chain:
    middlewares:
      - name: traefik-middleware-secure-headers-matrix
      - name: traefik-middleware-compress
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-cryptpad
spec:
  chain:
    middlewares:
      - name: traefik-middleware-secure-headers-cryptpad
      - name: traefik-middleware-compress
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-meet
spec:
  chain:
    middlewares:
      - name: traefik-middleware-secure-headers-meet
      - name: traefik-middleware-compress
