{
 "title": "Speedtest",
 "tags": [ "network" ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(speedtest_download_bits_per_second[3h])"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(speedtest_upload_bits_per_second[3h])"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(speedtest_ping_latency_milliseconds[3h])"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(speedtest_jitter_latency_milliseconds[3h])"
    }
   ]
  },
  {
   "title": "Last run",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - timestamp(last_over_time(speedtest_up[24h]))"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second",
     "legendFormat": "Download"
    },
    {
     "expr": "speedtest_upload_bits_per_second",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "Ping"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds",
     "legendFormat": "Jitter"
    }
   ]
  }
 ]
}